import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { createHash, randomUUID } from "node:crypto";
import { spawn } from "node:child_process";
import { serializeFileUpdate, writeJsonFileAtomic } from "./pipeline_file_io.mjs";
import { isCurrentProcessRunning } from "./pipeline_run_lock.mjs";

const cacheDirectory = (cacheRoot) => path.join(cacheRoot, "youtube-upload-audio1");
const normalizedPath = (value) => {
  const resolved = path.resolve(value);
  return process.platform === "win32" ? resolved.toLowerCase() : resolved;
};
const sourceIdentity = (recording) => ({
  path: path.resolve(recording.path),
  size: Number(recording.size),
  modifiedAtMs: Number(recording.modifiedAtMs),
});
const sameSource = (left, right) => typeof right?.path === "string" && normalizedPath(left.path) === normalizedPath(right.path) &&
  left.size === right.size && left.modifiedAtMs === right.modifiedAtMs;
const outputIdentity = (stat) => ({ size: stat.size, modifiedAtMs: stat.mtimeMs, changedAtMs: stat.ctimeMs });

export const buildTrack1UploadCopyPath = (recording, cacheRoot) => {
  const source = sourceIdentity(recording);
  const fingerprint = createHash("sha256").update(JSON.stringify({ ...source, path: normalizedPath(source.path) })).digest("hex").slice(0, 24);
  const base = path.parse(recording.path).name.replace(/[<>:"/\\|?*\x00-\x1F]/g, "_").replace(/\s+/g, " ").trim().slice(0, 72) || "recording";
  return path.join(cacheDirectory(cacheRoot), `${base}.${fingerprint}.track1.mkv`);
};

const verifySource = async (source) => {
  const stat = await fs.stat(source.path);
  if (!stat.isFile() || !sameSource(source, { path: source.path, size: stat.size, modifiedAtMs: stat.mtimeMs })) {
    throw Object.assign(new Error("Recording source changed; defer upload preparation until it is stable."), { code: "SOFTUCHIVE_UPLOAD_SOURCE_CHANGED" });
  }
};

const readManifest = async (manifestPath) => {
  try { return JSON.parse(await fs.readFile(manifestPath, "utf8")); }
  catch (error) { if (error.code === "ENOENT" || error instanceof SyntaxError) return null; throw error; }
};

const makeRecording = (outputPath, manifestPath, stat, source, cacheReused) => ({
  path: outputPath,
  name: path.basename(outputPath),
  size: stat.size,
  modifiedAtMs: stat.mtimeMs,
  originalPath: source.path,
  generatedForYouTubeUploadOnly: true,
  uploadCopyManifestPath: manifestPath,
  cacheReused,
});

export const ensureTrack1UploadCopy = async (recording, { cacheRoot, prepare, hasUploadSession = async () => false }) => {
  const source = sourceIdentity(recording);
  const outputPath = buildTrack1UploadCopyPath(recording, cacheRoot);
  const manifestPath = `${outputPath}.json`;
  if (normalizedPath(outputPath) === normalizedPath(source.path)) throw new Error("Upload copy cannot replace its source.");
  return serializeFileUpdate(outputPath, async () => {
    await verifySource(source);
    const manifest = await readManifest(manifestPath);
    if (manifest?.version === 1 && sameSource(source, manifest.source)) {
      const stat = await fs.stat(outputPath).catch((error) => { if (error.code === "ENOENT") return null; throw error; });
      if (stat?.isFile() && stat.size > 0 && JSON.stringify(outputIdentity(stat)) === JSON.stringify(manifest.output)) {
        await verifySource(source);
        return makeRecording(outputPath, manifestPath, stat, source, true);
      }
    }
    // A resumable session names these exact media bytes. Rebuilding first would
    // destroy its source before the uploader can reject the new fingerprint.
    // An unreadable checkpoint must also reject here, preserving all evidence.
    if (await hasUploadSession(outputPath)) {
      throw Object.assign(new Error("Saved upload requires its original prepared media. The cached copy or completion record is missing or changed; preserve the media and upload checkpoint for verification."), {
        code: "SOFTUCHIVE_UPLOAD_COPY_UNVERIFIED",
      });
    }
    await fs.mkdir(path.dirname(outputPath), { recursive: true });
    const partialPath = `${outputPath}.${process.pid}.${randomUUID()}.partial.mkv`;
    try {
      await prepare(partialPath);
      await verifySource(source);
      const partialStat = await fs.stat(partialPath);
      if (!partialStat.isFile() || partialStat.size <= 0) throw new Error("Prepared upload copy is empty or invalid.");
      // Commit the generated bytes before a durable completion manifest can
      // promise they are suitable for a later resumable upload.
      const media = await fs.open(partialPath, "r+");
      try { await media.sync(); }
      finally { await media.close(); }
      await fs.rename(partialPath, outputPath);
      const stat = await fs.stat(outputPath);
      await writeJsonFileAtomic(manifestPath, { version: 1, source, output: outputIdentity(stat), completedAt: new Date().toISOString() }, { durable: true });
      return makeRecording(outputPath, manifestPath, stat, source, false);
    } finally {
      await fs.rm(partialPath, { force: true });
    }
  });
};

// A complete copy may belong to an unfinished upload of any age. Only abandoned
// preparation/manifest temporaries can be removed without consulting the journal.
export const cleanupStaleUploadCopyPartials = async (cacheRoot, { staleAgeMs = 12 * 60 * 60 * 1000, log = () => {} } = {}) => {
  const directory = cacheDirectory(cacheRoot);
  const entries = await fs.readdir(directory, { withFileTypes: true }).catch((error) => { if (error.code === "ENOENT") return []; throw error; });
  for (const entry of entries) {
    if (!entry.isFile()) continue;
    const match = entry.name.match(/\.track1\.mkv(?:\.json)?\.(\d+)\.[a-f0-9-]+\.(?:partial\.mkv|tmp)$/i);
    if (!match || isCurrentProcessRunning(Number(match[1]))) continue;
    const target = path.join(directory, entry.name);
    try {
      const stat = await fs.stat(target);
      if (Date.now() - stat.mtimeMs < staleAgeMs) continue;
      await fs.rm(target, { force: true });
      log(`Removed abandoned upload preparation: ${target}`);
    } catch (error) {
      log(`Could not remove abandoned upload preparation ${target}: ${error.message}`);
    }
  }
};

export const removeUploadCopy = async (recording) => {
  const outputPath = recording?.path;
  const originalPath = recording?.originalPath;
  const manifestPath = recording?.uploadCopyManifestPath;
  if (!recording?.generatedForYouTubeUploadOnly || !outputPath || !originalPath ||
      manifestPath !== `${outputPath}.json` || normalizedPath(outputPath) === normalizedPath(originalPath) ||
      normalizedPath(manifestPath) === normalizedPath(originalPath)) {
    throw new Error("Only a generated upload copy can be removed; source recordings are protected.");
  }
  await serializeFileUpdate(outputPath, async () => {
    await fs.rm(outputPath, { force: true });
    await fs.rm(manifestPath, { force: true });
  });
};

export const runTrack1Remux = ({ sourcePath, outputPath, ffmpegPath, shouldPause, pauseIntervalMs = 1000,
  spawnProcess = spawn, setPriority = os.setPriority }) => new Promise((resolve, reject) => {
  const args = ["-y", "-i", sourcePath, "-map", "0:v?", "-map", "0:a:0?", "-sn", "-dn", "-c", "copy", outputPath];
  const child = spawnProcess(ffmpegPath, args, { stdio: "inherit", windowsHide: true });
  let failure = null;
  let settled = false;
  let checking = false;
  let pauseTimer = null;
  const requestStop = (error) => {
    if (settled || failure) return;
    failure = error;
    try { child.kill(); } catch {}
  };
  child.once("spawn", () => {
    try { setPriority(child.pid, os.constants.priority.PRIORITY_BELOW_NORMAL); } catch {}
  });
  child.once("error", (error) => {
    failure ||= new Error(`Failed to run ffmpeg (${ffmpegPath}): ${error.message}`);
  });
  child.once("close", (code) => {
    settled = true;
    if (pauseTimer) clearInterval(pauseTimer);
    if (failure) reject(failure);
    else if (code !== 0) reject(new Error(`Failed to create track 1 upload copy (ffmpeg exit code ${code}).`));
    else resolve();
  });
  if (shouldPause) {
    pauseTimer = setInterval(() => {
      if (checking || settled || failure) return;
      checking = true;
      Promise.resolve().then(shouldPause).then((paused) => {
        if (paused) requestStop(Object.assign(new Error("Pause requested while preparing the upload copy."), { code: "SOFTUCHIVE_PAUSED" }));
      }).catch(requestStop).finally(() => { checking = false; });
    }, pauseIntervalMs);
    pauseTimer.unref?.();
  }
});
